### ISSUE TITLE
Re-using translations

### ISSUE THREAD

**Issue by SumeetR** [bloodyowl/react-translate#4]
Hey Matthias,

I have another suggestion for improvement, say I have a button in one part of my app that says "Register" and in some other part there is a title that is also "Register". Currently the translation file would look like this (simplified to only include relevant entries):

```
Foo:
  REGISTER: "Register"
Bar:
  REGISTER: "Register"
```

It would be nice to able to reuse the translation and hence, for example, replace one of the entries in the translation file with some kind of identifier to "pick-up" the translation from another part:

```
Foo:
  REGISTER: "Register"
Bar:
  REGISTER: "{Foo.Register}"
```

What do you think?
S.
